targets:
  - name: home-assistant
    host_addr: http://192.168.1.20
    path: /api/webhook/someurl
    host_port: 8123
  - name: hubitat
    host_addr: http://192.168.1.21
    path: /data
    host_port: 39501
server:
  port: 8123
  path: /api/webhook/someurl
