targets:
  - name: home-assistant
    host_addr: http://192.168.10.142:8123/api/webhook/12345890jklfd89043jkl
  # the following is untested for hubitat at this point because I don't have one yet.
  - name: hubitat
    host_addr: http://192.168.1.21/data
    path: /data
server:
  port: 8123
  path: /api/webhook/someurl
  verbose: false
  # Set this to true to skip tls verification when sending data to targets.
  # Don't set this to true in production.
  tls_insecure_skip_verify: false
